# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-30 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('subtitle', models.CharField(max_length=60)),
                ('isbn10', models.CharField(max_length=10)),
                ('isbn13', models.CharField(max_length=13)),
                ('author', models.CharField(max_length=80)),
                ('transtr', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=60)),
                ('pubdate', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pages', models.IntegerField(default=0)),
                ('update_time', models.CharField(max_length=10)),
                ('create_time', models.CharField(max_length=10)),
                ('quantity', models.SmallIntegerField(default=1)),
                ('binding', models.SmallIntegerField(default=1)),
                ('series', models.CharField(max_length=40)),
                ('keywords', models.CharField(max_length=40)),
                ('summary', models.CharField(max_length=200)),
                ('authorintro', models.CharField(max_length=200)),
                ('status', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
