# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-30 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20161130_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='update_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
