# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-22 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('books', models.ManyToManyField(to='books.Book')),
            ],
        ),
    ]
